apiVersion: batch/v1
kind: Job
metadata:
  name: hangout-sql-batch-deployment
spec:
  template:
    metadata:
      name: hangout-mysql-Job
      labels:
        app: hangout-sql-batch
    spec:
      containers:
        - name: hangout-batch-container
          image: camil/mysqldump
          envFrom:
          - configMapRef:
             name: hangout-config
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
               name: mysql-pass
               key: password
                   mysql --user="${DB_USER}" --password="${DB_PASSWORD}" --host="${DB_HOST}" "$@" "${DB_NAME}" < /mysqldump/$db.sql
          command: [ "mysql" ]
          args: ["-hhangout-mysql-service", "-uroot", "-pmilind123"]
          volumeMounts:
          - name: hangout-persistent-storage
            mountPath: /var/lib/mysql
      restartPolicy: Never
      volumes:
      - name: hangout-persistent-storage
        persistentVolumeClaim:
         claimName: hangout-pvc
      restartPolicy: Never
