apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hangout-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extention/v1beta1
    kind: Deployment
    name: hangoutapp
  targetCPUUtilizationPercentage: 20
